name: Sync with Upstream

on:
#   schedule:
#     - cron: "0 0 * * *" #every 24 hours
  repository_dispatch:   

jobs:
 merge-upstream-master:
   runs-on: [ubuntu-latest]
   steps:
     - uses: geertvdc/setup-hub@master
     - name: Clone repo
       run: |
         git clone https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git

     - name: Merge Upstream Master
       working-directory: ./impacket_static_binaries
       run: |
         git config --local user.name githubactions
         git config --local user.email rflathers@gmail.com
         git remote add upstream https://github.com/SecureAuthCorp/impacket.git
         git fetch upstream
         git merge --no-ff --no-commit upstream/master || echo "resolving conflicts"
         git reset HEAD README.md .github #never change these
         git checkout -- README.md .github
         if ! (git diff --cached --exit-code > /dev/null); then # test if something changed
            git commit -m "merged upstream/master"
            git push origin master
         else
            echo "Nothing changed!"
         fi
     
     - name: Check for new release
       env:
          GITHUB_USER: ${{ secrets.GITHUB_USER }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
       working-directory: ./impacket_static_binaries
       run: |
         latestUpstreamRelease=($(hub release -L 1|cut -d_ -f2-))
         myReleases=($(git branch --list --all |grep "origin/release-"|cut -d- -f2-))
         if [[ " ${myReleases[@]} " =~ " ${latestUpstreamRelease} " ]]; then
            echo "Releases are up to date"
            exit 0
         else
            git checkout impacket_$latestUpstreamRelease
            git checkout -b release-$latestUpstreamRelease
            git push --set-upstream origin release-$latestUpstreamRelease
         fi
         
         
         
